version: "3.4"

services:
  nodeapp:
    container_name: eva_backend
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "3001:3001"
    networks:
      - node-mongo-network
  mongo:
    container_name: mongoserver
    image: mongo:4.4.6
    restart: always
    command: [--auth]
    ports:
      - "28018:27017"
    volumes:
      - mongodb_vol:/data/db
    networks:
      - node-mongo-network

networks:
  node-mongo-network:
    driver: bridge

volumes:
  mongodb_vol:
