version: "3"

services:
  backend:
    container_name: eva-backend
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongoserver
    image: mongo:4.4.6
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - mongodb_vol:/data/db

volumes:
  mongodb_vol:
